### ISSUE TITLE
15-09-23: session disconnection

### ISSUE THREAD

**Issue by 5XS** [anxety-solo/sd-webui-colab#1]
Теперь крашает. Вчера не было крашей

**Comment by lyminkareaktorskaya** [comment]
Брат, ты делаешь великое дело, не сдавайся, нагибай гугл. Помни - ты герой анонов

**Comment by 5XS** [comment]
> Брат, ты делаешь великое дело, не сдавайся, нагибай гугл. Помни - ты герой анонов

он легенда

**Comment by anxety-solo** [comment]
Не знаю, удастся ли мне все это сделать сегодня, так как работает нестабильно - первый запуск работает минут 40 и более, а следующий запуск - выключение примерно через 10 минут (я полагаюсь на этот промежуток времени, часто на нём происходит сбой сессии).

**Comment by 5XS** [comment]
@anxety-solo Оно вроде отключило, но не уверен на сто процентов что это из-за WebUI, так как там была не красная кнопка, а серая кнопка.

**Comment by 5XS** [comment]
Если еще будет дисконнект, сообщу здесь

**Comment by 5XS** [comment]
@anxety-solo Опять дисконнект

**Comment by lyminkareaktorskaya** [comment]
Тоже дисконнект

**Comment by romper-pain** [comment]
привет! heads up, this colab has worked without disconnecting for me the past 2 days. it's in chinese, i think the webui is clunky, and it's hard to find the public url when its ready, but it's worked so far

https://github.com/s4afa451dgf415f/colab_stable_diffusion

now if chr∗s p∗rry is reading this, then i was actually kidding
